DROP TABLE tech_news CASCADE CONSTRAINTS;
DROP TABLE daily_knowledge CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;

CREATE TABLE users (
                       id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email           VARCHAR2(255) NOT NULL UNIQUE,
                       password        VARCHAR2(255) NOT NULL,
                       name            VARCHAR2(100) NOT NULL,
                       role            VARCHAR2(20) NOT NULL,
                       status          VARCHAR2(20) DEFAULT 'ACTIVE',
                       created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_role ON users(role);

CREATE TABLE daily_knowledge (
                                 id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 knowledge_date  DATE NOT NULL,
                                 category        VARCHAR2(50) NOT NULL,
                                 title           VARCHAR2(255) NOT NULL,
                                 summary         CLOB NOT NULL,
                                 detail          CLOB NOT NULL,
                                 created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                                 CONSTRAINT uk_daily_knowledge_date UNIQUE (knowledge_date)
);

CREATE INDEX idx_daily_knowledge_date ON daily_knowledge(knowledge_date);
CREATE INDEX idx_daily_knowledge_category ON daily_knowledge(category);

CREATE TABLE tech_news (
                           id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           news_date       DATE NOT NULL,
                           source          VARCHAR2(100) NOT NULL,
                           title           VARCHAR2(255) NOT NULL,
                           url             VARCHAR2(500) NOT NULL,
                           summary         CLOB NOT NULL,
                           created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                           CONSTRAINT uk_tech_news_url UNIQUE (url)
);

CREATE INDEX idx_tech_news_date ON tech_news(news_date);
CREATE INDEX idx_tech_news_source ON tech_news(source);

ALTER SYSTEM REGISTER;




INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail)
VALUES (
           DATE '2026-04-01',
           'Backend',
           'Spring Boot 트랜잭션 이해',
           '트랜잭션 전파와 격리 수준에 대한 기본 개념 정리',
           'Spring에서는 @Transactional을 통해 트랜잭션을 관리한다. 전파 옵션(REQUIRED, REQUIRES_NEW 등)에 따라 트랜잭션 동작이 달라지며, 격리 수준에 따라 데이터 정합성에 영향을 준다.'
       );

INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail)
VALUES (
           DATE '2026-04-02',
           'Database',
           '인덱스 설계 전략',
           '조회 성능 향상을 위한 인덱스 설계 방법',
           '인덱스는 WHERE, JOIN, ORDER BY에 사용되는 컬럼 위주로 생성해야 하며, 과도한 인덱스는 오히려 성능을 저하시킬 수 있다.'
       );

INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail)
VALUES (
           DATE '2026-04-03',
           'Java',
           'Stream API 사용법',
           'Java Stream을 활용한 데이터 처리',
           'Stream API를 사용하면 반복문 없이 데이터 가공이 가능하다. map, filter, collect 등을 활용하여 가독성과 생산성을 높일 수 있다.'
       );

INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail)
VALUES (
           DATE '2026-04-04',
           'Infra',
           'Docker 기본 개념',
           '컨테이너 기반 배포 방식 이해',
           'Docker는 애플리케이션을 컨테이너 단위로 패키징하여 환경 차이를 최소화한다. 이미지와 컨테이너 개념을 이해하는 것이 중요하다.'
       );


--

INSERT INTO tech_news (news_date, source, title, url, summary)
VALUES (
           DATE '2026-04-01',
           'ZDNet',
           '오픈AI 신규 모델 발표',
           'https://example.com/news1',
           '오픈AI가 성능이 향상된 새로운 LLM 모델을 발표했다.'
       );

INSERT INTO tech_news (news_date, source, title, url, summary)
VALUES (
           DATE '2026-04-02',
           'TechCrunch',
           '구글 AI 서비스 업데이트',
           'https://example.com/news2',
           '구글이 생성형 AI 기능을 Gmail과 Docs에 통합했다.'
       );

INSERT INTO tech_news (news_date, source, title, url, summary)
VALUES (
           DATE '2026-04-03',
           'The Verge',
           '애플, AI 전략 강화',
           'https://example.com/news3',
           '애플이 온디바이스 AI 기능 강화를 위한 전략을 발표했다.'
       );

INSERT INTO tech_news (news_date, source, title, url, summary)
VALUES (
           DATE '2026-04-04',
           'Hacker News',
           '개발자 생산성 도구 인기 상승',
           'https://example.com/news4',
           '코드 자동 생성 및 리뷰 도구가 개발자들 사이에서 빠르게 확산되고 있다.'
       );






INSERT INTO DAILY.USERS (
    EMAIL,
    PASSWORD,
    NAME,
    ROLE,
    STATUS
) VALUES (
             'test@daily.com',
             '1234', -- BCrypt 암호 (예시: 1234)
             '테스트유저',
             'USER',
             'ACTIVE'
         );

COMMIT;


SELECT * FROM DAILY_KNOWLEDGE dk ;



INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail, created_at)  VALUES (DATE '2026-04-07', 'Java', 'Optional 활용법', 'Null 처리 개선', 'Optional을 사용하면 NullPointerException을 방지할 수 있다.', SYSTIMESTAMP);

INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail, created_at)  VALUES (DATE '2026-04-08', 'Infra', 'CI/CD 개념', '자동 배포 이해', 'CI/CD는 빌드, 테스트, 배포를 자동화한다.', SYSTIMESTAMP);

INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail, created_at)  VALUES (DATE '2026-04-09', 'Backend', 'REST API 설계', 'RESTful 설계 원칙', 'HTTP Method와 URI 설계가 중요하다.', SYSTIMESTAMP);

INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail, created_at)  VALUES (DATE '2026-04-10', 'Database', '트랜잭션 로그', '데이터 복구', '트랜잭션 로그를 통해 장애 복구가 가능하다.', SYSTIMESTAMP);

INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail, created_at)  VALUES (DATE '2026-04-11', 'Java', 'Lambda 표현식', '간결한 코드 작성', '람다식을 통해 코드 가독성을 높인다.', SYSTIMESTAMP);

INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail, created_at)  VALUES (DATE '2026-04-12', 'Infra', 'Kubernetes', '컨테이너 관리', '컨테이너 오케스트레이션 도구이다.', SYSTIMESTAMP);

INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail, created_at)  VALUES (DATE '2026-04-13', 'Backend', 'JPA 영속성', '엔티티 관리', '영속성 컨텍스트는 1차 캐시를 제공한다.', SYSTIMESTAMP);

INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail, created_at)  VALUES (DATE '2026-04-14', 'Database', '조인 전략', '쿼리 성능', 'Nested Loop, Hash Join을 상황에 맞게 선택한다.', SYSTIMESTAMP);

INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail, created_at)  VALUES (DATE '2026-04-15', 'Java', '컬렉션 프레임워크', '자료구조 이해', 'List, Set, Map의 차이를 이해해야 한다.', SYSTIMESTAMP);

INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail, created_at)  VALUES (DATE '2026-04-16', 'Infra', '로드밸런싱', '트래픽 분산', '요청을 여러 서버로 분산한다.', SYSTIMESTAMP);

INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail, created_at)  VALUES (DATE '2026-04-17', 'Backend', 'DTO vs Entity', '계층 분리', 'DTO는 전달용, Entity는 DB 매핑용이다.', SYSTIMESTAMP);

INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail, created_at)  VALUES (DATE '2026-04-18', 'Database', '인덱스 구조', '검색 최적화', 'B-Tree 인덱스가 일반적으로 사용된다.', SYSTIMESTAMP);

INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail, created_at)  VALUES (DATE '2026-04-19', 'Java', 'Exception 처리', '예외 전략', 'Checked와 Unchecked 예외를 구분해야 한다.', SYSTIMESTAMP);

INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail, created_at)  VALUES (DATE '2026-04-20', 'Infra', '모니터링', '시스템 관리', 'CPU, Memory 사용량을 모니터링한다.', SYSTIMESTAMP);

INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail, created_at)  VALUES (DATE '2026-04-21', 'Backend', 'AOP', '공통 로직 분리', '횡단 관심사를 분리한다.', SYSTIMESTAMP);

INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail, created_at)  VALUES (DATE '2026-04-22', 'Database', '락', '동시성 제어', '데이터 정합성을 유지한다.', SYSTIMESTAMP);

INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail, created_at)  VALUES (DATE '2026-04-23', 'Java', 'Thread', '멀티스레드', '병렬 처리를 가능하게 한다.', SYSTIMESTAMP);

INSERT INTO daily_knowledge (knowledge_date, category, title, summary, detail, created_at)  VALUES (DATE '2026-04-24', 'Infra', 'DNS', '도메인 해석', '도메인을 IP로 변환하는 시스템이다.', SYSTIMESTAMP);



COMMIT;




SELECT * FROM PROMPT_TEMPLATE pt ;




SELECT * FROM daily_knowledge ORDER BY KNOWLEDGE_DATE ;

SELECT * FROM TECH_NEWS tn ORDER BY created_at desc;

SELECT * FROM crawl_schedule;
